name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag to publish (e.g., v1.0.0)'
        required: true
        type: string

env:
  REGISTRY_URL: registry.npmjs.org

jobs:
  publish-npm:
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install dependencies
      run: bun install
      
    - name: Make index.ts executable
      run: chmod +x index.ts
      
    - name: Verify package.json
      run: |
        echo "Package name: $(node -p "require('./package.json').name")"
        echo "Version: $(node -p "require('./package.json').version")"
        echo "Binary: $(node -p "require('./package.json').bin?.ghswitch")"
        
    - name: Run NPM pack dry-run
      run: npm pack --dry-run
      
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
    - name: Verify NPM package
      run: |
        echo "Waiting for NPM to propagate..."
        sleep 30
        npm view ghswitch version || echo "Package may still be propagating"

  test-npm-install:
    name: Test NPM Installation
    needs: publish-npm
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Setup Bun (for testing)
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Wait for NPM propagation
      run: sleep 60
      
    - name: Test NPM installation
      run: |
        echo "Testing NPM installation..."
        npm install -g ghswitch
        ghswitch --version
        
    - name: Test Bun installation
      if: runner.os != 'Windows'
      run: |
        echo "Testing Bun installation..."
        npm uninstall -g ghswitch
        bun install -g ghswitch
        ghswitch --version
        
    - name: Cleanup
      run: |
        npm uninstall -g ghswitch || true
        bun remove -g ghswitch || true
